export const recordsExampleOne = [
  {
    x: 639.4504870648182,
    y: -68.37213237868224,
    rotation: 0,
    opacity: 1,
    id: 'shape:HyJbgrd0W0T12tV73TF6C',
    type: 'geo',
    props: {
      w: 500.0762960258769,
      h: 114.882392330269,
      geo: 'rectangle',
      color: 'black',
      labelColor: 'black',
      fill: 'none',
      dash: 'draw',
      size: 'm',
      font: 'draw',
      text: 'Step 1',
      align: 'middle',
      verticalAlign: 'middle',
      url: '',
    },
    index: 'a1',
    typeName: 'shape',
  },
  {
    x: -205.27298595186573,
    y: 650.2059686675099,
    rotation: 0,
    opacity: 1,
    id: 'shape:bBKkSkmAWfpaOYbEg_uaN',
    type: 'geo',
    props: {
      w: 554.1385982989448,
      h: 114.882392330269,
      geo: 'rectangle',
      color: 'black',
      labelColor: 'black',
      fill: 'none',
      dash: 'draw',
      size: 'm',
      font: 'draw',
      text: 'Step 5',
      align: 'middle',
      verticalAlign: 'middle',
      url: '',
    },
    index: 'a2',
    typeName: 'shape',
  },
  {
    x: 616.9245277843733,
    y: 695.2578872283998,
    rotation: 0,
    opacity: 1,
    id: 'shape:G3TCHm1so_9o_4dWHW5kk',
    type: 'arrow',
    index: 'a2G',
    props: {
      dash: 'draw',
      size: 'm',
      fill: 'none',
      color: 'black',
      labelColor: 'black',
      bend: 0,
      start: { type: 'point', x: 0, y: 0 },
      end: {
        type: 'binding',
        boundShapeId: 'shape:bBKkSkmAWfpaOYbEg_uaN',
        normalizedAnchor: {
          x: 0.9959349593495933,
          y: 0.450980392156865,
        },
        isPrecise: true,
        isExact: false,
      },
      arrowheadStart: 'none',
      arrowheadEnd: 'arrow',
      text: 'Edge Label 2',
      font: 'draw',
    },
    typeName: 'shape',
  },
  {
    x: 1117.00082381025,
    y: 936.2856515291603,
    rotation: 0,
    opacity: 1,

    id: 'shape:2zyTpxNbhsIGa5FCgBTCX',
    type: 'arrow',
    index: 'a2V',
    props: {
      dash: 'draw',
      size: 'm',
      fill: 'none',
      color: 'black',
      labelColor: 'black',
      bend: 0,
      start: {
        type: 'binding',
        boundShapeId: 'shape:bBKkSkmAWfpaOYbEg_uaN',
        normalizedAnchor: {
          x: 0.9909909909909911,
          y: 0.4901960784313742,
        },
        isPrecise: false,
        isExact: false,
      },
      end: {
        type: 'binding',
        boundShapeId: 'shape:HyJbgrd0W0T12tV73TF6C',
        normalizedAnchor: {
          x: 0.09009009009008988,
          y: 0.4705882352941171,
        },
        isPrecise: true,
        isExact: false,
      },
      arrowheadStart: 'none',
      arrowheadEnd: 'arrow',
      text: 'Edge Label 1',
      font: 'draw',
    },
    typeName: 'shape',
  },
  {
    x: 619.1771237124176,
    y: 638.9429890272875,
    rotation: 0,
    opacity: 1,

    id: 'shape:6J0hXVtFqufm7I_l_pzo0',
    type: 'geo',
    props: {
      w: 500.0762960258769,
      h: 114.882392330269,
      geo: 'rectangle',
      color: 'black',
      labelColor: 'black',
      fill: 'none',
      dash: 'draw',
      size: 'm',
      font: 'draw',
      text: 'Step 4',
      align: 'middle',
      verticalAlign: 'middle',
      url: '',
    },
    index: 'a3',
    typeName: 'shape',
  },
  {
    x: 625.9349114965512,
    y: 373.1366695180378,
    rotation: 0,
    opacity: 1,

    id: 'shape:qHfG4IN3399NDuN4k6R6W',
    type: 'geo',
    props: {
      w: 500.0762960258769,
      h: 114.882392330269,
      geo: 'rectangle',
      color: 'black',
      labelColor: 'black',
      fill: 'none',
      dash: 'draw',
      size: 'm',
      font: 'draw',
      text: '',
      align: 'middle',
      verticalAlign: 'middle',
      url: '',
    },
    index: 'a4',
    typeName: 'shape',
  },
  {
    x: 860.2048880131781,
    y: 488.01906184830676,
    rotation: 0,
    opacity: 1,

    id: 'shape:hxXvpYw7iIS_w3Y-V9Adm',
    type: 'arrow',
    index: 'a4G',
    props: {
      dash: 'draw',
      size: 'm',
      fill: 'none',
      color: 'black',
      labelColor: 'black',
      bend: 0,
      start: {
        type: 'binding',
        boundShapeId: 'shape:qHfG4IN3399NDuN4k6R6W',
        normalizedAnchor: {
          x: 0.46846846846846824,
          y: 0.9999999999999996,
        },
        isPrecise: false,
        isExact: false,
      },
      end: {
        type: 'binding',
        boundShapeId: 'shape:6J0hXVtFqufm7I_l_pzo0',
        normalizedAnchor: {
          x: 0.5135135135135135,
          y: 0.07843137254902043,
        },
        isPrecise: true,
        isExact: false,
      },
      arrowheadStart: 'none',
      arrowheadEnd: 'arrow',
      text: '',
      font: 'draw',
    },
    typeName: 'shape',
  },
  {
    x: 860.2048880131779,
    y: 271.7698527560357,
    rotation: 0,
    opacity: 1,

    id: 'shape:baVPHsNB0QQjOvekD09VD',
    type: 'arrow',
    index: 'a4V',
    props: {
      dash: 'draw',
      size: 'm',
      fill: 'none',
      color: 'black',
      labelColor: 'black',
      bend: 0,
      start: {
        type: 'point',
        x: 9.238039683629381,
        y: -6.757787784133541,
      },
      end: {
        type: 'binding',
        boundShapeId: 'shape:qHfG4IN3399NDuN4k6R6W',
        normalizedAnchor: {
          x: 0.4835315199771913,
          y: 0.09849927483462421,
        },
        isPrecise: true,
        isExact: false,
      },
      arrowheadStart: 'none',
      arrowheadEnd: 'arrow',
      text: '',
      font: 'draw',
    },
    typeName: 'shape',
  },
  {
    x: 623.6823155685067,
    y: 143.37188485749982,
    rotation: 0,
    opacity: 1,

    id: 'shape:HC1bpkrpGtVvRgG2FL-vb',
    type: 'geo',
    props: {
      w: 500.0762960258769,
      h: 114.882392330269,
      geo: 'rectangle',
      color: 'black',
      labelColor: 'black',
      fill: 'none',
      dash: 'draw',
      size: 'm',
      font: 'draw',
      text: 'Step 2',
      align: 'middle',
      verticalAlign: 'middle',
      url: '',
    },
    index: 'a5',
    typeName: 'shape',
  },
  {
    x: 864.710079869267,
    y: 44.25766402354225,
    rotation: 0,
    opacity: 1,

    id: 'shape:cA2fDz2Y3QUO2_rvWMN_G',
    type: 'arrow',
    index: 'a5V',
    props: {
      dash: 'draw',
      size: 'm',
      fill: 'none',
      color: 'black',
      labelColor: 'black',
      bend: 0,
      start: {
        type: 'binding',
        boundShapeId: 'shape:HyJbgrd0W0T12tV73TF6C',
        normalizedAnchor: {
          x: 0.45045045045045007,
          y: 0.980392156862745,
        },
        isPrecise: false,
        isExact: false,
      },
      end: {
        type: 'binding',
        boundShapeId: 'shape:HC1bpkrpGtVvRgG2FL-vb',
        normalizedAnchor: { x: 0.5, y: 0.5 },
        isPrecise: true,
        isExact: false,
      },
      arrowheadStart: 'none',
      arrowheadEnd: 'arrow',
      text: '',
      font: 'draw',
    },
    typeName: 'shape',
  },
  {
    x: 820.8965536625922,
    y: 422.26195448308584,
    rotation: 0,
    opacity: 1,

    id: 'shape:_vgxH13R9_MQZeQla-4jY',
    type: 'text',
    props: {
      color: 'black',
      size: 'm',
      w: 78.61666870117188,
      text: 'Step 3',
      font: 'draw',
      align: 'middle',
      autoSize: true,
      scale: 1,
    },
    index: 'a6',
    typeName: 'shape',
  },
]

export const recordsExampleTwo = [
  {
    x: 200,
    y: 100,
    rotation: 0,
    opacity: 1,
    meta: {},
    id: 'shape:1',
    type: 'geo',
    props: {
      w: 500,
      h: 100,
      geo: 'rectangle',
      color: 'black',
      labelColor: 'black',
      fill: 'none',
      dash: 'draw',
      size: 'm',
      font: 'draw',
      text: 'Heart pumps blood effectively',
      align: 'middle',
      verticalAlign: 'middle',
      url: '',
    },
    index: 'a1',
    typeName: 'shape',
  },
  {
    x: 200,
    y: 300,
    rotation: 0,
    opacity: 1,
    meta: {},
    id: 'shape:2',
    type: 'geo',
    props: {
      w: 500,
      h: 100,
      geo: 'rectangle',
      color: 'black',
      labelColor: 'black',
      fill: 'none',
      dash: 'draw',
      size: 'm',
      font: 'draw',
      text: 'Heartbeat becomes erratic due to electrical disturbance',
      align: 'middle',
      verticalAlign: 'middle',
      url: '',
    },
    index: 'a2',
    typeName: 'shape',
  },
  {
    x: 200,
    y: 500,
    rotation: 0,
    opacity: 1,
    meta: {},
    id: 'shape:3',
    type: 'geo',
    props: {
      w: 500,
      h: 100,
      geo: 'rectangle',
      color: 'black',
      labelColor: 'black',
      fill: 'none',
      dash: 'draw',
      size: 'm',
      font: 'draw',
      text: 'Heart stops pumping blood effectively',
      align: 'middle',
      verticalAlign: 'middle',
      url: '',
    },
    index: 'a3',
    typeName: 'shape',
  },
  {
    x: 200,
    y: 700,
    rotation: 0,
    opacity: 1,
    meta: {},
    id: 'shape:4',
    type: 'geo',
    props: {
      w: 500,
      h: 100,
      geo: 'rectangle',
      color: 'black',
      labelColor: 'black',
      fill: 'none',
      dash: 'draw',
      size: 'm',
      font: 'draw',
      text: 'Lack of oxygenated blood flow to the brain leads to unconsciousness',
      align: 'middle',
      verticalAlign: 'middle',
      url: '',
    },
    index: 'a4',
    typeName: 'shape',
  },
  {
    x: 200,
    y: 900,
    rotation: 0,
    opacity: 1,
    meta: {},
    id: 'shape:5',
    type: 'geo',
    props: {
      w: 500,
      h: 100,
      geo: 'rectangle',
      color: 'black',
      labelColor: 'black',
      fill: 'none',
      dash: 'draw',
      size: 'm',
      font: 'draw',
      text: 'Cardiac arrest leads to death without immediate treatment',
      align: 'middle',
      verticalAlign: 'middle',
      url: '',
    },
    index: 'a5',
    typeName: 'shape',
  },
  {
    x: 450,
    y: 200,
    rotation: 0,
    opacity: 1,
    meta: {},
    id: 'shape:1-2',
    type: 'arrow',
    index: 'a6',
    props: {
      dash: 'draw',
      size: 'm',
      fill: 'none',
      color: 'black',
      labelColor: 'black',
      bend: 0,
      start: {
        type: 'binding',
        boundShapeId: 'shape:1',
        normalizedAnchor: {
          x: 0.5,
          y: 1,
        },
        isPrecise: true,
        isExact: false,
      },
      end: {
        type: 'binding',
        boundShapeId: 'shape:2',
        normalizedAnchor: {
          x: 0.5,
          y: 0,
        },
        isPrecise: true,
        isExact: false,
      },
      arrowheadStart: 'none',
      arrowheadEnd: 'arrow',
      text: '',
      font: 'draw',
    },
    typeName: 'shape',
  },
  {
    x: 450,
    y: 400,
    rotation: 0,
    opacity: 1,
    meta: {},
    id: 'shape:2-3',
    type: 'arrow',
    index: 'a7',
    props: {
      dash: 'draw',
      size: 'm',
      fill: 'none',
      color: 'black',
      labelColor: 'black',
      bend: 0,
      start: {
        type: 'binding',
        boundShapeId: 'shape:2',
        normalizedAnchor: {
          x: 0.5,
          y: 1,
        },
        isPrecise: true,
        isExact: false,
      },
      end: {
        type: 'binding',
        boundShapeId: 'shape:3',
        normalizedAnchor: {
          x: 0.5,
          y: 0,
        },
        isPrecise: true,
        isExact: false,
      },
      arrowheadStart: 'none',
      arrowheadEnd: 'arrow',
      text: '',
      font: 'draw',
    },
    typeName: 'shape',
  },
  {
    x: 450,
    y: 600,
    rotation: 0,
    opacity: 1,
    meta: {},
    id: 'shape:3-4',
    type: 'arrow',
    index: 'a8',
    props: {
      dash: 'draw',
      size: 'm',
      fill: 'none',
      color: 'black',
      labelColor: 'black',
      bend: 0,
      start: {
        type: 'binding',
        boundShapeId: 'shape:3',
        normalizedAnchor: {
          x: 0.5,
          y: 1,
        },
        isPrecise: true,
        isExact: false,
      },
      end: {
        type: 'binding',
        boundShapeId: 'shape:4',
        normalizedAnchor: {
          x: 0.5,
          y: 0,
        },
        isPrecise: true,
        isExact: false,
      },
      arrowheadStart: 'none',
      arrowheadEnd: 'arrow',
      text: '',
      font: 'draw',
    },
    typeName: 'shape',
  },
  {
    x: 450,
    y: 800,
    rotation: 0,
    opacity: 1,
    meta: {},
    id: 'shape:4-5',
    type: 'arrow',
    index: 'a9',
    props: {
      dash: 'draw',
      size: 'm',
      fill: 'none',
      color: 'black',
      labelColor: 'black',
      bend: 0,
      start: {
        type: 'binding',
        boundShapeId: 'shape:4',
        normalizedAnchor: {
          x: 0.5,
          y: 1,
        },
        isPrecise: true,
        isExact: false,
      },
      end: {
        type: 'binding',
        boundShapeId: 'shape:5',
        normalizedAnchor: {
          x: 0.5,
          y: 0,
        },
        isPrecise: true,
        isExact: false,
      },
      arrowheadStart: 'none',
      arrowheadEnd: 'arrow',
      text: '',
      font: 'draw',
    },
    typeName: 'shape',
  },
]
